export const APPOINTMENT_LIST = [
  {
    tokenNumber: "CAR12",
    parchaaId: "123214314",
    name: "Jaiprakash Kushwaha",
    gender: "Male",
    age: "25",
    chiefComplaint: "hair fall",
    tags: ["baby deliveries"],
    visitStatus: "Upcoming",
  },
  {
    tokenNumber: "CAR13",
    parchaaId: "223214315",
    name: "Anjali Sharma",
    gender: "Female",
    age: "30",
    chiefComplaint: "back pain",
    tags: ["physical therapy"],
    visitStatus: "Completed",
  },
  {
    tokenNumber: "CAR14",
    parchaaId: "323214316",
    name: "Rohit Verma",
    gender: "Male",
    age: "40",
    chiefComplaint: "migraine",
    tags: ["Initial Consultation", "neurology"],
    visitStatus: "Upcoming",
  },
  {
    tokenNumber: "CAR15",
    parchaaId: "423214317",
    name: "Sonal Gupta",
    gender: "Female",
    age: "35",
    chiefComplaint: "allergy",
    tags: ["Skin Test", "seasonal"],
    visitStatus: "Cancelled",
  },
  {
    tokenNumber: "CAR16",
    parchaaId: "523214318",
    name: "Amit Singh",
    gender: "Others",
    age: "50",
    chiefComplaint: "hypertension",
    tags: ["Blood Pressure Check", "medication review"],
    visitStatus: "Upcoming",
  },
  {
    tokenNumber: "CAR17",
    parchaaId: "623214319",
    name: "Priya Joshi",
    gender: "Female",
    age: "28",
    chiefComplaint: "diabetes management",
    tags: ["Diet Consultation", "routine checkup"],
    visitStatus: "Completed",
  },
  {
    tokenNumber: "CAR18",
    parchaaId: "723214320",
    name: "Karan Patel",
    gender: "Male",
    age: "32",
    chiefComplaint: "knee pain",
    tags: ["Orthopedic", "MRI Scan"],
    visitStatus: "No Show",
  },
  {
    tokenNumber: "CAR19",
    parchaaId: "823214321",
    name: "Deepika Rao",
    gender: "Female",
    age: "45",
    chiefComplaint: "asthma",
    tags: ["Pulmonary Function Test", "medication adjustment"],
    visitStatus: "Completed",
  },
  {
    tokenNumber: "CAR20",
    parchaaId: "923214322",
    name: "Vikram Malhotra",
    gender: "Male",
    age: "55",
    chiefComplaint: "chest pain",
    tags: ["Cardiology", "ECG"],
    visitStatus: "Upcoming",
  },
  {
    tokenNumber: "CAR21",
    parchaaId: "1023214323",
    name: "Meera Kapoor",
    gender: "Female",
    age: "60",
    chiefComplaint: "arthritis",
    tags: ["Pain Management", "physiotherapy"],
    visitStatus: "Cancelled",
  },
  {
    tokenNumber: "CAR22",
    parchaaId: "1123214324",
    name: "Suresh Reddy",
    gender: "Male",
    age: "47",
    chiefComplaint: "insomnia",
    tags: ["Sleep Study", "behavioral therapy"],
    visitStatus: "Upcoming",
  },
  {
    tokenNumber: "CAR23",
    parchaaId: "1223214325",
    name: "Neha Desai",
    gender: "Female",
    age: "26",
    chiefComplaint: "skin rash",
    tags: ["Dermatology", "allergy test"],
    visitStatus: "Completed",
  },
  {
    tokenNumber: "CAR24",
    parchaaId: "1323214326",
    name: "Arjun Nair",
    gender: "Male",
    age: "37",
    chiefComplaint: "toothache",
    tags: ["Dental Checkup", "X-Ray"],
    visitStatus: "Upcoming",
  },
  {
    tokenNumber: "CAR23",
    parchaaId: "1223214325",
    name: "Neha Desai",
    gender: "Female",
    age: "26",
    chiefComplaint: "skin rash",
    tags: ["Dermatology", "allergy test"],
    visitStatus: "Completed",
  },
  {
    tokenNumber: "CAR24",
    parchaaId: "1323214326",
    name: "Arjun Nair",
    gender: "Male",
    age: "37",
    chiefComplaint: "toothache",
    tags: ["Dental Checkup", "X-Ray"],
    visitStatus: "Upcoming",
  },
  {
    tokenNumber: "CAR23",
    parchaaId: "1223214325",
    name: "Neha Desai",
    gender: "Female",
    age: "26",
    chiefComplaint: "skin rash",
    tags: ["Dermatology", "allergy test"],
    visitStatus: "Completed",
  },
  {
    tokenNumber: "CAR24",
    parchaaId: "1323214326",
    name: "Arjun Nair",
    gender: "Male",
    age: "37",
    chiefComplaint: "toothache",
    tags: ["Dental Checkup", "X-Ray"],
    visitStatus: "Upcoming",
  },
];
