export const DATA = [
  {
    id: 1,
    name: "John Doe",
    age: 27,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 40.712776,
    longitude: -74.005974,
    gender: "Male",
    state: "New York",
    address: "New York",
    district: "Manhattan",
    city: "New York City",
    tehsil: "Tehsil A",
    bloodGroup: "AB-",
    registrationTag: "babyDelivery",
    registrationDate: "12-01-2025",
    registeredBy: "Jaiprakash",
    lastAppointmentDate: "15-01-2025",
    upcomingAppointmentDate: "25-01-2025",
    lastChiefComplaint: "fever",
    currentChiefComplaint: "headache",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 34,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 34.052235,
    longitude: -118.243683,
    gender: "Female",
    state: "California",
    address: "Los Angeles",
    district: "LA County",
    city: "Los Angeles",
    tehsil: "Tehsil B",
    bloodGroup: "O+",
    registrationTag: "routineCheckup",
    registrationDate: "10-02-2025",
    registeredBy: "Michael",
    lastAppointmentDate: "20-02-2025",
    upcomingAppointmentDate: "05-03-2025",
    lastChiefComplaint: "cough",
    currentChiefComplaint: "sore throat",
  },
  {
    id: 3,
    name: "Alice Johnson",
    age: 29,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 41.878113,
    longitude: -87.629799,
    gender: "Female",
    state: "Illinois",
    address: "Chicago",
    district: "Cook County",
    city: "Chicago",
    tehsil: "Tehsil C",
    bloodGroup: "A+",
    registrationTag: "followUp",
    registrationDate: "15-03-2025",
    registeredBy: "Sarah",
    lastAppointmentDate: "22-03-2025",
    upcomingAppointmentDate: "30-03-2025",
    lastChiefComplaint: "back pain",
    currentChiefComplaint: "muscle strain",
  },
  {
    id: 4,
    name: "Bob Brown",
    age: 45,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 29.760427,
    longitude: -95.369804,
    gender: "Male",
    state: "Texas",
    address: "Houston",
    district: "Harris County",
    city: "Houston",
    tehsil: "Tehsil D",
    bloodGroup: "B-",
    registrationTag: "emergency",
    registrationDate: "20-04-2025",
    registeredBy: "Emily",
    lastAppointmentDate: "25-04-2025",
    upcomingAppointmentDate: "10-05-2025",
    lastChiefComplaint: "chest pain",
    currentChiefComplaint: "shortness of breath",
  },
  {
    id: 5,
    name: "Charlie Davis",
    age: 38,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 39.739236,
    longitude: -104.990251,
    gender: "Male",
    state: "Colorado",
    address: "Denver",
    district: "Denver County",
    city: "Denver",
    tehsil: "Tehsil E",
    bloodGroup: "AB+",
    registrationTag: "annualCheckup",
    registrationDate: "05-05-2025",
    registeredBy: "David",
    lastAppointmentDate: "10-05-2025",
    "up comingAppointmentDate": "20-05-2025",
    lastChiefComplaint: "fatigue",
    currentChiefComplaint: "dizziness",
  },
  {
    id: 6,
    name: "Diana Evans",
    age: 26,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 36.169941,
    longitude: -115.139832,
    gender: "Female",
    state: "Nevada",
    address: "Las Vegas",
    district: "Clark County",
    city: "Las Vegas",
    tehsil: "Tehsil F",
    bloodGroup: "O-",
    registrationTag: "checkup",
    registrationDate: "15-06-2025",
    registeredBy: "Laura",
    lastAppointmentDate: "20-06-2025",
    upcomingAppointmentDate: "30-06-2025",
    lastChiefComplaint: "nausea",
    currentChiefComplaint: "vomiting",
  },
  {
    id: 7,
    name: "Ethan White",
    age: 31,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 32.715736,
    longitude: -117.161087,
    gender: "Male",
    state: "California",
    address: "San Diego",
    district: "San Diego County",
    city: "San Diego",
    tehsil: "Tehsil G",
    bloodGroup: "B+",
    registrationTag: "routineCheckup",
    registrationDate: "25-07-2025",
    registeredBy: "Chris",
    lastAppointmentDate: "30-07-2025",
    upcomingAppointmentDate: "15-08-2025",
    lastChiefComplaint: "headache",
    currentChiefComplaint: "migraine",
  },
  {
    id: 8,
    name: "Fiona Green",
    age: 22,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 40.73061,
    longitude: -73.935242,
    gender: "Female",
    state: "New York",
    address: "Brooklyn",
    district: "Kings County",
    city: "New York City",
    tehsil: "Tehsil H",
    bloodGroup: "AB-",
    registrationTag: "newPatient",
    registrationDate: "01-09-2025",
    registeredBy: "Tom",
    lastAppointmentDate: "10-09-2025",
    upcomingAppointmentDate: "20-09-2025",
    lastChiefComplaint: "anxiety",
    currentChiefComplaint: "stress",
  },
  {
    id: 9,
    name: "George Black",
    age: 40,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 37.774929,
    longitude: -122.419418,
    gender: "Male",
    state: "California",
    address: "San Francisco",
    district: "San Francisco County",
    city: "San Francisco",
    tehsil: "Tehsil I",
    bloodGroup: "O+",
    registrationTag: "followUp",
    registrationDate: "15-10-2025",
    registeredBy: "Anna",
    lastAppointmentDate: "20-10-2025",
    upcomingAppointmentDate: "05-11-2025",
    lastChiefComplaint: "high blood pressure",
    currentChiefComplaint: "chest discomfort",
  },
  {
    id: 10,
    name: "Hannah Blue",
    age: 35,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 39.961176,
    longitude: -82.998794,
    gender: "Female",
    state: "Ohio",
    address: "Columbus",
    district: "Franklin County",
    city: "Columbus",
    tehsil: "Tehsil J",
    bloodGroup: "A-",
    registrationTag: "annualCheckup",
    registrationDate: "20-11-2025",
    registeredBy: "Robert",
    lastAppointmentDate: "25-11-2025",
    upcomingAppointmentDate: "10-12-2025",
    lastChiefComplaint: "joint pain",
    currentChiefComplaint: "swelling",
  },
  {
    id: 11,
    name: "Ian Gray",
    age: 28,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 30.267153,
    longitude: -97.743057,
    gender: "Male",
    state: "Texas",
    address: "Austin",
    district: "Travis County",
    city: "Austin",
    tehsil: "Tehsil K",
    bloodGroup: "AB+",
    registrationTag: "checkup",
    registrationDate: "15-12-2025",
    registeredBy: "Jessica",
    lastAppointmentDate: "20-12-2025",
    upcomingAppointmentDate: "05-01-2026",
    lastChiefComplaint: "fatigue",
    currentChiefComplaint: "weakness",
  },
  {
    id: 12,
    name: "Julia White",
    age: 33,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 36.162663,
    longitude: -86.781601,
    gender: "Female",
    state: "Tennessee",
    address: "Nashville",
    district: "Davidson County",
    city: "Nashville",
    tehsil: "Tehsil L",
    bloodGroup: "O-",
    registrationTag: "routineCheckup",
    registrationDate: "10-01-2026",
    registeredBy: "Mark",
    lastAppointmentDate: "15-01-2026",
    upcomingAppointmentDate: "01-02-2026",
    lastChiefComplaint: "headache",
    currentChiefComplaint: "nausea",
  },
  {
    id: 13,
    name: "Kevin Brown",
    age: 50,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 39.739236,
    longitude: -104.990251,
    gender: "Male",
    state: "Colorado",
    address: "Denver",
    district: "Denver County",
    city: "Denver",
    tehsil: "Tehsil M",
    bloodGroup: "B+",
    registrationTag: "emergency",
    registrationDate: "20-02-2026",
    registeredBy: "Nancy",
    lastAppointmentDate: "25-02-2026",
    upcomingAppointmentDate: "10-03-2026",
    lastChiefComplaint: "chest pain",
    currentChiefComplaint: "breathing difficulty",
  },
  {
    id: 14,
    name: "Laura Green",
    age: 24,
    thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
    latitude: 34.052235,
    longitude: -118.243683,
    gender: "Female",
    state: "California",
    address: "Los Angeles",
    district: "LA County",
    city: "Los Angeles",
    tehsil: "Tehsil N",
    bloodGroup: "A+",
    registrationTag: "newPatient",
    registrationDate: "15-03-2026",
    registeredBy: "Paul",
    lastAppointmentDate: "20-03-2026",
    upcomingAppointmentDate: "05-04-2026",
    lastChiefComplaint: "anxiety",
    currentChiefComplaint: "stress",
  },
];
