export const TEMPLATE_LIST = [
  {
    templateName: "headache",
    prescriptionData: {
      chiefComplaints: ["Severe headache for 2 days"],
      diagnosis: ["Migraine"],
      medications: [
        {
          medication: "Ibuprofen",
          dose: "200",
          measurement: "mg",
          timing: "After meals",
          frequency: "1-1-1",
          duration: "5 days",
        },
        {
          medication: "Sumatriptan",
          dose: "50",
          measurement: "mg",
          timing: "At onset of headache",
          frequency: "As needed",
          duration: "As needed",
        },
      ],
      labTest: ["CT Scan"],
      instructions: "Avoid bright lights and loud noises",
      notes: "Patient experiences aura before headache",
      followUp: "In 1 week",
    },
  },
  {
    templateName: "cold",
    prescriptionData: {
      chiefComplaints: ["Runny nose, sneezing, sore throat"],
      diagnosis: ["Common Cold"],
      medications: [
        {
          medication: "Cetirizine",
          dose: "10",
          measurement: "mg",
          timing: "Before bedtime",
          frequency: "1-0-0",
          duration: "7 days",
        },
        {
          medication: "Paracetamol",
          dose: "500",
          measurement: "mg",
          timing: "As needed",
          frequency: "1-1-1",
          duration: "5 days",
        },
      ],
      labTest: [],
      instructions: "Stay hydrated, rest well",
      notes: "No fever, symptoms are mild",
      followUp: "If symptoms persist after 7 days",
    },
  },
  {
    templateName: "flu",
    prescriptionData: {
      chiefComplaints: ["Fever, body aches, fatigue"],
      diagnosis: ["Influenza"],
      medications: [
        {
          medication: "Oseltamivir",
          dose: "75",
          measurement: "mg",
          timing: "With food",
          frequency: "1-0-1",
          duration: "5 days",
        },
        {
          medication: "Ibuprofen",
          dose: "400",
          measurement: "mg",
          timing: "As needed",
          frequency: "1-1-1",
          duration: "3 days",
        },
      ],
      labTest: ["Flu test"],
      instructions: "Rest, increase fluid intake",
      notes: "Flu vaccination status unknown",
      followUp: "In 5 days if no improvement",
    },
  },
  {
    templateName: "stomach ache",
    prescriptionData: {
      chiefComplaints: ["Abdominal pain, nausea"],
      diagnosis: ["Gastritis"],
      medications: [
        {
          medication: "Omeprazole",
          dose: "20",
          measurement: "mg",
          timing: "Before breakfast",
          frequency: "1-0-0",
          duration: "14 days",
        },
        {
          medication: "Antacid",
          dose: "10",
          measurement: "ml",
          timing: "After meals",
          frequency: "1-1-1",
          duration: "As needed",
        },
      ],
      labTest: ["H. Pylori test"],
      instructions: "Avoid spicy food and caffeine",
      notes: "History of similar symptoms",
      followUp: "In 2 weeks",
    },
  },
  {
    templateName: "allergy",
    prescriptionData: {
      chiefComplaints: ["Itchy eyes, sneezing, hives"],
      diagnosis: ["Allergic Rhinitis"],
      medications: [
        {
          medication: "Loratadine",
          dose: "10",
          measurement: "mg",
          timing: "Anytime",
          frequency: "1-0-0",
          duration: "As needed",
        },
        {
          medication: "Diphenhydramine",
          dose: "25",
          measurement: "mg",
          timing: "Before bedtime",
          frequency: "1-0-0",
          duration: "As needed",
        },
      ],
      labTest: ["Allergy test"],
      instructions: "Avoid known allergens",
      notes: "Patient has a pet cat",
      followUp: "If symptoms worsen",
    },
  },
  {
    templateName: "back pain",
    prescriptionData: {
      chiefComplaints: ["Lower back pain"],
      diagnosis: ["Lumbar Strain"],
      medications: [
        {
          medication: "Acetaminophen",
          dose: "500",
          measurement: "mg",
          timing: "As needed",
          frequency: "1-1-1",
          duration: "7 days",
        },
        {
          medication: "Cyclobenzaprine",
          dose: "10",
          measurement: "mg",
          timing: "At bedtime",
          frequency: "0-0-1",
          duration: "7 days",
        },
      ],
      labTest: ["X-ray"],
      instructions: "Avoid heavy lifting, use hot/cold packs",
      notes: "Patient's job involves manual labor",
      followUp: "In 1 week",
    },
  },
  {
    templateName: "fever",
    prescriptionData: {
      chiefComplaints: ["High temperature, chills"],
      diagnosis: ["Viral Infection"],
      medications: [
        {
          medication: "Paracetamol",
          dose: "500",
          measurement: "mg",
          timing: "As needed",
          frequency: "1-1-1",
          duration: "3 days",
        },
        {
          medication: "Ibuprofen",
          dose: "200",
          measurement: "mg",
          timing: "As needed",
          frequency: "1-1-1",
          duration: "3 days",
        },
      ],
      labTest: ["Blood test"],
      instructions: "Drink plenty of fluids, rest",
      notes: "No other symptoms reported",
      followUp: "If fever persists for more than 3 days",
    },
  },
  {
    templateName: "diabetes",
    prescriptionData: {
      chiefComplaints: ["Frequent urination, thirst"],
      diagnosis: ["Type 2 Diabetes"],
      medications: [
        {
          medication: "Metformin",
          dose: "500",
          measurement: "mg",
          timing: "With meals",
          frequency: "1-0-1",
          duration: "Ongoing",
        },
        {
          medication: "Glibenclamide",
          dose: "5",
          measurement: "mg",
          timing: "Before breakfast",
          frequency: "1-0-0",
          duration: "Ongoing",
        },
      ],
      labTest: ["HbA1c"],
      instructions: "Monitor blood glucose levels",
      notes: "Family history of diabetes",
      followUp: "In 3 months",
    },
  },
  {
    templateName: "hypertension",
    prescriptionData: {
      chiefComplaints: ["Headache, dizziness"],
      diagnosis: ["Hypertension"],
      medications: [
        {
          medication: "Amlodipine",
          dose: "5",
          measurement: "mg",
          timing: "Anytime",
          frequency: "1-0-0",
          duration: "Ongoing",
        },
        {
          medication: "Lisinopril",
          dose: "10",
          measurement: "mg",
          timing: "Anytime",
          frequency: "1-0-0",
          duration: "Ongoing",
        },
      ],
      labTest: ["Blood pressure monitoring"],
      instructions: "Reduce salt intake, exercise regularly",
      notes: "Patient is overweight",
      followUp: "In 1 month",
    },
  },
  {
    templateName: "asthma",
    prescriptionData: {
      chiefComplaints: ["Shortness of breath, wheezing"],
      diagnosis: ["Asthma"],
      medications: [
        {
          medication: "Albuterol",
          dose: "90",
          measurement: "mcg",
          timing: "As needed",
          frequency: "Up to 4 times a day",
          duration: "As needed",
        },
        {
          medication: "Fluticasone",
          dose: "100",
          measurement: "mcg",
          timing: "Morning and night",
          frequency: "1-0-1",
          duration: "Ongoing",
        },
      ],
      labTest: ["Spirometry"],
      instructions: "Avoid triggers, use inhaler correctly",
      notes: "Patient has a history of asthma",
      followUp: "In 2 weeks",
    },
  },
];
