export const PATIENT_DATA = {
  noOfDuePatientForFollowUp: 1234,
  noOfPatientsWithScheduledBabyDeliveries: 642,
  patientFlaggedForVaccination: 980,
  patientFlaggedForTest: 726,
  patientsReferredToSpecialisedCare: 91277,
  genderRatioBreakdown: { male: "49.7%", female: "45%", others: "5.3%" },
  topDiagnosis: [
    {
      dengue_fever: "10.3%",
      hypertension: "15.7%",
      chikungunya: "15%",
      typhoid_fever: "4.7%",
      diabetes: "8.9%",
      tuberculosis: "3%",
      arthritis: "7%",
    },
  ],
  ageRatioBreakDown: {
    children: "7.52%",
    youngAdults: "13.15%",
    adults: "28.13%",
    elders: "51.23%",
  },
};

export const upcomingAppointments = [
  {
    patientId: "1238",
    mmuNo: "1",
    chiefComplaint: "chest pain",
    comorbidity: "Diabetes",
    medications: [
      "Albuterol",
      "Prednisone",
      "Azithromycin",
      "Amoxiciline",
      "Dolo-650",
      "Paracetamal",
      "citirizine",
    ],
    labInvestigations: ["ECG", "Blood glucose"],
    followUpDate: "24-12-2024",
  },
  {
    patientId: "1240",
    mmuNo: "2",
    chiefComplaint: "headache",
    comorbidity: "Hypertension",
    medications: ["Ibuprofen", "Atenolol"],
    labInvestigations: ["MRI", "Blood pressure check"],
    followUpDate: "15-01-2025",
  },
  {
    patientId: "1241",
    mmuNo: "3",
    chiefComplaint: "back pain",
    comorbidity: "Arthritis",
    medications: ["Naproxen", "Methotrexate"],
    labInvestigations: ["X-ray", "CBC"],
    followUpDate: "03-02-2025",
  },
  {
    patientId: "1242",
    mmuNo: "4",
    chiefComplaint: "shortness of breath",
    comorbidity: "COPD",
    medications: ["Tiotropium", "Fluticasone"],
    labInvestigations: ["Spirometry", "Chest X-ray"],
    followUpDate: "12-02-2025",
  },
  {
    patientId: "1243",
    mmuNo: "5",
    chiefComplaint: "abdominal pain",
    comorbidity: "IBS",
    medications: ["Omeprazole", "Dicyclomine"],
    labInvestigations: ["Ultrasound", "Stool test"],
    followUpDate: "21-02-2025",
  },
  {
    patientId: "1244",
    mmuNo: "6",
    chiefComplaint: "dizziness",
    comorbidity: "Vertigo",
    medications: ["Meclizine", "Betahistine"],
    labInvestigations: ["Audiometry", "CT scan"],
    followUpDate: "01-03-2025",
  },
  {
    patientId: "1245",
    mmuNo: "7",
    chiefComplaint: "fatigue",
    comorbidity: "Anemia",
    medications: ["Ferrous sulfate", "Vitamin B12"],
    labInvestigations: ["Complete blood count", "Ferritin level"],
    followUpDate: "15-03-2025",
  },
  {
    patientId: "1246",
    mmuNo: "8",
    chiefComplaint: "joint pain",
    comorbidity: "Rheumatoid arthritis",
    medications: ["Ibuprofen", "Methotrexate"],
    labInvestigations: ["Rheumatoid factor", "ESR"],
    followUpDate: "25-03-2025",
  },
  {
    patientId: "1247",
    mmuNo: "9",
    chiefComplaint: "fever",
    comorbidity: "None",
    medications: ["Paracetamol", "Hydration"],
    labInvestigations: ["Blood culture", "WBC count"],
    followUpDate: "05-04-2025",
  },
  {
    patientId: "1248",
    mmuNo: "10",
    chiefComplaint: "nausea",
    comorbidity: "Gastritis",
    medications: ["Ondansetron", "Pantoprazole"],
    labInvestigations: ["Endoscopy", "Helicobacter pylori test"],
    followUpDate: "14-04-2025",
  },
  {
    patientId: "1249",
    mmuNo: "11",
    chiefComplaint: "cough",
    comorbidity: "Asthma",
    medications: ["Albuterol", "Montelukast"],
    labInvestigations: ["Pulmonary function test", "Chest X-ray"],
    followUpDate: "22-04-2025",
  },
  {
    patientId: "1250",
    mmuNo: "12",
    chiefComplaint: "rash",
    comorbidity: "Eczema",
    medications: ["Hydrocortisone cream", "Cetirizine"],
    labInvestigations: ["Skin biopsy", "Allergy test"],
    followUpDate: "30-04-2025",
  },
  {
    patientId: "1251",
    mmuNo: "13",
    chiefComplaint: "sore throat",
    comorbidity: "None",
    medications: ["Amoxicillin", "Throat lozenges"],
    labInvestigations: ["Throat swab", "CBC"],
    followUpDate: "10-05-2025",
  },
];
